
CREATE TABLE EMPLOYEE(EMP_ID INT,ENAME VARCHAR(20),JOB_DESC VARCHAR(25),
SALARY INT,HIRE_DATE date);

INSERT INTO EMPLOYEE VALUES(1,'RAM','ADMIN',100000,DATE '2024-02-02');
INSERT INTO EMPLOYEE VALUES(2,'george','MANAGER',200000,DATE '2024-02-02');
INSERT INTO EMPLOYEE VALUES(3,'Aravind','SALES',300000,DATE '2024-02-02');
INSERT INTO EMPLOYEE VALUES(4,'Nivetha','SALES',250000,DATE '2024-02-02');
INSERT INTO EMPLOYEE VALUES(5,'Hussain','HR',350000,DATE '2024-02-02');


SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE ORDER BY JOB_DESC;

-- AVERAGE SALARY FOR EACH DEPARTMENT
SELECT JOB_DESC,AVG(SALARY) FROM EMPLOYEE GROUP BY JOB_DESC; 

-- Count the number of employees in each department
SELECT JOB_DESC,COUNT(EMP_ID) FROM EMPLOYEE GROUP BY JOB_DESC;


SELECT JOB_DESC,COUNT(EMP_ID) 
FROM EMPLOYEE
GROUP BY JOB_DESC
HAVING COUNT(EMP_ID)>1
ORDER BY JOB_DESC;
 
 SELECT JOB_DESC,COUNT(EMP_ID) 
 FROM EMPLOYEE WHERE SALARY>400000
 GROUP BY JOB_DESC
 HAVING COUNT(EMP_ID)>1
 ORDER BY JOB_DESC;
 
 /**WHERE USED TO FILTER ROWS**/
 /**HAVING USED TO FILTER FROM THE GROUPBY DATA**/
