create database DataAnalaytics;

use DataAnalaytics;

CREATE TABLE Persons (
    PersonID int,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255)
);

INSERT INTO Persons values(1,"Gopalakrishnan","Remya","Apartment","Chennai");

INSERT INTO Persons values(2,"krishnan","RemyaGopal","ewfrewf","CIT"),
(3,"Aravind","Gopal","Pudhuper","Chennai");

SELECT * FROM PERSONS;


use dataanalaytics;



DELETE FROM PERSONS WHERE PERSONID=2;

UPDATE PERSONS SET FIRSTNAME='NIVETHIKA' WHERE PERSONID=1;


use dataanalaytics;

-- create new table product 
CREATE TABLE PRODUCTS(PRODUCTID INT,PRODUCTNAME VARCHAR(20),PRICE INT);

-- query to insert values in the table
INSERT INTO PRODUCTS VALUES(1,'BIKE',200000),(2,'BIKE1',300000);


SELECT * FROM PRODUCTS;

INSERT INTO PRODUCTS VALUES(1,'BIKE',200000),(2,'BIKE21',400000);

INSERT INTO PRODUCTS VALUES(1,'BIKE3',600000);
-- QUERY TO FIND OUT THE MINIMUM VALUE FROM THE SPECIFIED COLUMN
SELECT MIN(PRICE)
FROM Products;

-- QUERY TO FIND OUT THE MAXIMUM VALUE FROM THE SPECIFIED COLUMN
SELECT MAX(Price)
FROM Products;


SELECT MAX(Price) AS SmallestPrice, PRODUCTID
FROM Products
GROUP BY PRODUCTID;

SELECT AVG(Price) AS SmallestPrice, PRODUCTID
FROM Products
GROUP BY PRODUCTID;

SELECT MAX(Price) AS SmallestPrice, PRODUCTID
FROM Products
GROUP BY PRODUCTID;

select * from products;
-- QUERY TO RETURN THE TOTAL NUMBER OF VALUES IN THAT COLUMN
-- AS(ALIAS) USED TO GIVE THE TEMPORARY NAME FOR THE OUPUT
SELECT COUNT(*) AS NUMBEROFCOLUMNS
FROM PRODUCTS;


-- QUERY TO FIND OUT THE COUNT OF PRODUCT WHOSE PRICE IS GREATER THAN 20000
SELECT COUNT(ProductID)
FROM Products
WHERE Price > 200000;

-- QUERY TO REMOVE THE DUPLICATE PRICE VALUE AND RETURN THE COUNT WIHTOUT DUPLICATE
SELECT COUNT(DISTINCT Price)
FROM Products;


-- SUM FUNCTION TO GET THE TOTAL OF ALL THE PRICES
SELECT SUM(PRICE)
FROM PRODUCTS;

-- QUERY TO FIND OUT THE AVERAGE OF ALL THE PRICES
SELECT AVG(Price)
FROM Products;